---

- name: enable partner repository
  replace:
    dest: '/etc/apt/sources.list'
    regexp: '^# (deb .* partner)$'
    replace: '\1'
    backup: yes
  notify: update apt cache

- name: install skype
  apt:
    name: 'skype'
    state: latest
  sudo: yes
