#!/usr/bin/ansible-playbook -K
---

- name: ubuntu desktop
  hosts: localhost
  connection: local
  gather_facts: true
  vars:
    packages_required:
      - curl
      - vim
      - htop
      - mc
      - terminator
      - gparted
      - gsmartcontrol
      - meld
      - git
      - ttf-mscorefonts-installer
      - ubuntu-restricted-extras
      - vlc
      - keepassx
      - unity-tweak-tool
      - rdesktop
      - gnome-rdp
      - virtualenv
      - virtualenvwrapper
      - python-dev
      - python-pip
      - libxml2-dev
      - libxslt1-dev
      - libz-dev
      - libffi-dev
      - libssl-dev
      - xclip
      - qemu-utils
    packages_blacklist:
      - whoopsie
      - command-not-found
      - nano

  tasks:
  - name: install required packages
    apt:
      name: '{{ item }}'
      state: 'present'
    with_items: packages_required
    sudo: yes

  - name: remove blacklisted packages
    apt:
      name: '{{ item }}'
      state: 'absent'
      purge: yes
    with_items: packages_blacklist
    sudo: yes

  roles:
  - { role: desktop_config, tags: ['desktop', 'config' ] }
#  - { role: ansible-sublime-text, tags: ['dev', 'editor' ] }
  - { role: ansible-vim, tags: [ 'editor' ] }
  - { role: ansible-indicator-multiload, tags: ['desktop', 'indicator' ] }
  - { role: ansible-indicator-sound-switcher, tags: ['desktop', 'indicator' ] }
  - { role: ansible-variety, tags: ['desktop', 'wallpaper' ] }
  - { role: ansible-skype, tags: ['desktop', 'voip' ] }
  - { role: ansible-virtualbox, tags: ['devops', 'virtualbox' ] }
  - { role: ansible-owncloud-client, tags: ['desktop', 'owncloud' ] }
#  - { role: ansible-mysql-workbench, tags: ['desktop', 'database' ] }
# http://dev.mysql.com/get/Downloads/MySQLGUITools/mysql-workbench-community-6.3.4-1ubu1504-amd64.deb
